[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "jinja2>=3.1.6",
    "pydantic-settings>=2.10.1",
    "pydantic>=2.11.9",
    "uvicorn>=0.35.0",
]
